name = "spinmachologin-net"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachologin.net"
HMAC_KEY = "692905f7e056c2acceeeed1e54e2ef05b1dea9fd96ebe307a4b4104fe62ccdf0"
COOKIE_NAME = "wg2"
PLAY_PATH = "discover"
BUTTON_ID = "pa9729ff5bed2ba9060026dff981d7d06"
GATE_SALT = "cc8b959fb7f9553c"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "25q4"
CTA_SELECTOR = ".play-button"
